# Generated by Django 4.1.4 on 2023-10-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userID", models.IntegerField(max_length=250)),
                ("ISBN", models.IntegerField(max_length=250)),
                ("bookRating", models.IntegerField(max_length=250)),
                ("bookTitle", models.CharField(max_length=500)),
                ("bookAuthor", models.CharField(max_length=500)),
                ("yearOfPublication", models.IntegerField(max_length=250)),
                ("publisher", models.CharField(max_length=500)),
                ("imageUrlS", models.URLField()),
                ("imageUrlM", models.URLField()),
                ("imageUrlL", models.URLField()),
                ("totalRatingCount", models.IntegerField()),
            ],
        ),
    ]
