# Generated by Django 4.1.4 on 2023-10-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ISBN", models.CharField(max_length=250)),
                ("bookTitle", models.CharField(max_length=500)),
                ("bookAuthor", models.CharField(max_length=500)),
                ("yearOfPublication", models.IntegerField()),
                ("publisher", models.CharField(max_length=500)),
                ("imageUrlS", models.URLField()),
                ("imageUrlM", models.URLField()),
                ("imageUrlL", models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name="book",
            name="ISBN",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="book",
            name="bookRating",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="book",
            name="userID",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="yearOfPublication",
            field=models.IntegerField(),
        ),
    ]
